# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'PPimgEdit' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for PPimgEdit


 pod 'GPUImage'

  target 'PPimgEditTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'PPimgEditUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
